MOV DPTR, #4500H
MOVX A, @DPTR
MOV R0, A
DEC R0
OUTER_LOOP:
	MOV A, R0
	MOV R1, A
	MOV DPTR, #4501H
	INNER_LOOP:
		MOVX A, @DPTR
		MOV B,A
		INC DPTR
		MOVX A, @DPTR
		CJNE A, B, EQUAL
		SJMP LOOP
		EQUAL:
			JNC LOOP
			DEC DPL
			MOVX @DPTR, A
			MOV A, B
			INC DPL
			MOVX @DPTR, A
			LOOP:
				DJNZ R1, INNER_LOOP
				DJNZ R0, OUTER_LOOP
HERE: SJMP HERE
END