ORG 0000H
	MOV DPTR, #4200H
	MOVX A, @DPTR
	MOV R0, #00H
	MOV R1, #00H
	MOV R2, #08H
	COUNT_LOOP:
		RLC A
		JC INCREMENT_ONES
		INC R1
		SJMP NEXT_BIT
		INCREMENT_ONES:
			INC R0
		NEXT_BIT:
			DJNZ R2, COUNT_LOOP
	MOV DPTR, #4201H
	MOV A, R0
	MOVX @DPTR, A
	INC DPTR
	MOV A, R1
	MOVX @DPTR, A
	HERE: SJMP HERE
END
