ORG 0000H
	MAIN:
		MOV A, 50H
		MOV R1, A
		MOV B, #01H
		FACTORIAL_LOOP:
			CJNE R1, #01H, MULTI
			SJMP STORE_RES
			MULTI:
				DEC R1
				MOV B, R1
				MUL AB
				SJMP FACTORIAL_LOOP
		STORE_RES:
			MOV 51H, A
	HERE: SJMP HERE
END